apiVersion: v1
kind: Namespace
metadata:
  name: kt-virtual-environment
---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-server-tls
  namespace: kt-virtual-environment
type: kubernetes.io/tls
data:
  tls.crt: TLS_CRT_B64_PLACEHOLDER
  tls.key: TLS_KEY_B64_PLACEHOLDER
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-server
  namespace: kt-virtual-environment
  labels:
    app: webhook-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-server
  template:
    metadata:
      labels:
        app: webhook-server
    spec:
      containers:
      - name: server
        image: virtualenvironment/virtual-env-admission-webhook:v0.2.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8443
          name: webhook-api
        volumeMounts:
        - name: webhook-tls-certs
          mountPath: /run/secrets/tls
          readOnly: true
      volumes:
      - name: webhook-tls-certs
        secret:
          secretName: webhook-server-tls
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-server
  namespace: kt-virtual-environment
spec:
  selector:
    app: webhook-server
  ports:
    - port: 443
      targetPort: webhook-api
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: virtual-environment-webhook
webhooks:
  - name: webhook-server.kt-virtual-environment.svc
    namespaceSelector:
      matchLabels:
        environment-tag-injection: enabled
    clientConfig:
      service:
        name: webhook-server
        namespace: kt-virtual-environment
        path: "/inject"
      caBundle: CA_PEM_B64_PLACEHOLDER
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
